// frontend/src/pages/Signup.vue
<template>
  <div class="signup-container">
    <div class="form-box">
      <h1 class="title">サインアップ（新規登録）</h1>
      
      <form @submit.prevent="handleSubmit" class="signup-form">
        <div class="form-control">
          <label class="form-label">メールアドレス</label>
          <input
            v-model="formData.email"
            type="email"
            class="form-input"
            required
          />
        </div>

        <div class="form-control">
          <label class="form-label">ユーザー名</label>
          <input
            v-model="formData.username"
            type="text"
            class="form-input"
            required
          />
        </div>

        <div class="form-control">
          <label class="form-label">パスワード</label>
          <input
            v-model="formData.password"
            type="password"
            class="form-input"
            required
          />
        </div>

        <div class="button-group">
          <button
            type="submit"
            class="btn btn-primary"
            :disabled="isLoading"
          >
            {{ isLoading ? '登録中...' : '登録する' }}
          </button>
          <router-link to="/" class="btn btn-secondary">
            キャンセル
          </router-link>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useAuthStore } from '@/stores/auth'
import { useRouter } from 'vue-router'

const router = useRouter()
const authStore = useAuthStore()
const isLoading = ref(false)

const formData = ref({
  email: '',
  username: '',
  password: ''
})

const handleSubmit = async () => {
  try {
    isLoading.value = true
    await authStore.register({
      email: formData.value.email,
      username: formData.value.username,
      password: formData.value.password
    })
    
    alert('確認メールを送信しました。メールを確認して登録を完了してください。')
    router.push('/login')
  } catch (error) {
    alert(error instanceof Error ? error.message : '予期せぬエラーが発生しました')
  } finally {
    isLoading.value = false
  }
}
</script>

<style scoped>
.signup-container {
  min-height: 100vh;
  padding: 2.5rem 1rem;
  background-color: var(--color-background);
  display: flex;
  justify-content: center;
  align-items: flex-start;
}

.form-box {
  background: white;
  padding: 2rem;
  border-radius: 0.5rem;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
  width: 100%;
  max-width: 32rem;
}

.title {
  font-size: 1.5rem;
  font-weight: bold;
  margin-bottom: 1.5rem;
  text-align: center;
}

.signup-form {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.button-group {
  display: flex;
  gap: 1rem;
  margin-top: 1rem;
}

.button-group .btn {
  flex: 1;
}

.btn:disabled {
  opacity: 0.7;
  cursor: not-allowed;
}
</style>

// frontend_old/src/app/signup/page.tsx
'use client'

import {
  Box,
  Button,
  Container,
  FormControl,
  FormLabel,
  Heading,
  Input,
  Stack,
  Text,
  useToast,
} from '@chakra-ui/react'
import { useForm } from 'react-hook-form'
import { useState } from 'react'
import { register as registerUser } from '@/services/auth'

type RegisterForm = {
  email: string
  username: string
  password: string
}

export default function Register() {
  const { register, handleSubmit, formState: { errors } } = useForm<RegisterForm>()
  const [isLoading, setIsLoading] = useState(false)
  const toast = useToast()

  const onSubmit = async (data: RegisterForm) => {
    try {
      setIsLoading(true)
      await registerUser(data)
      toast({
        title: '確認メールを送信しました',
        description: 'メールを確認して登録を完了してください',
        status: 'success',
      })
    } catch (error) {
      toast({
        title: '登録に失敗しました',
        description: error instanceof Error ? error.message : '予期せぬエラーが発生しました',
        status: 'error',
      })
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <Container maxW="container.sm" py={10}>
      <Box bg="white" p={8} borderRadius="lg" boxShadow="md">
        <Stack spacing={6}>
          <Heading size="lg">サインアップ（新規登録）</Heading>
          <form onSubmit={handleSubmit(onSubmit)}>
            <Stack spacing={4}>
              <FormControl isRequired>
                <FormLabel>メールアドレス</FormLabel>
                <Input
                  type="email"
                  {...register('email', { required: true })}
                />
              </FormControl>
              <FormControl isRequired>
                <FormLabel>ユーザー名</FormLabel>
                <Input
                  {...register('username', { required: true })}
                />
              </FormControl>
              <FormControl isRequired>
                <FormLabel>パスワード</FormLabel>
                <Input
                  type="password"
                  {...register('password', { required: true })}
                />
              </FormControl>
              <Button
                type="submit"
                colorScheme="brand"
                size="lg"
                isLoading={isLoading}
              >
                登録する
              </Button>
            </Stack>
          </form>
        </Stack>
      </Box>
    </Container>
  )
}
